"""
Subtitle Generator and Formatter for MoneyPrinterTurbo.
Generates SRT (SubRip) and ASS (Advanced SubStation Alpha) files with timing, fonts, and positioning.
"""

from __future__ import annotations

import html
from pathlib import Path
import re
from typing import List, Optional

from app.core.logging_config import logger
from app.engines.money_printer_turbo.models import ScriptSegment, SubtitleStyle


class SubtitleManager:
    """
    Manages subtitle timing compilation, SRT/ASS export, and FFmpeg filter string generation.
    """

    @classmethod
    def format_timestamp_srt(cls, seconds: float) -> str:
        """Converts seconds into SRT timestamp format: HH:MM:SS,mmm"""
        hrs = int(seconds // 3600)
        mins = int((seconds % 3600) // 60)
        secs = int(seconds % 60)
        millis = int((seconds - int(seconds)) * 1000)
        return f"{hrs:02d}:{mins:02d}:{secs:02d},{millis:03d}"

    @classmethod
    def format_timestamp_ass(cls, seconds: float) -> str:
        """Converts seconds into ASS timestamp format: H:MM:SS.cc"""
        hrs = int(seconds // 3600)
        mins = int((seconds % 3600) // 60)
        secs = int(seconds % 60)
        centis = int((seconds - int(seconds)) * 100)
        return f"{hrs:d}:{mins:02d}:{secs:02d}.{centis:02d}"

    @classmethod
    def generate_srt(
        cls,
        segments: List[ScriptSegment],
        output_path: Path,
    ) -> Path:
        """
        Exports segments to a standard .srt subtitle file.
        """
        output_path.parent.mkdir(parents=True, exist_ok=True)
        lines: List[str] = []

        for idx, seg in enumerate(segments, start=1):
            start_str = cls.format_timestamp_srt(seg.start_second)
            end_str = cls.format_timestamp_srt(seg.end_second)
            text_clean = seg.text.strip()

            lines.append(str(idx))
            lines.append(f"{start_str} --> {end_str}")
            lines.append(text_clean)
            lines.append("")  # Empty separator line

        output_path.write_text("\n".join(lines), encoding="utf-8")
        logger.info(f"Generated SRT subtitles ({len(segments)} segments) → {output_path}")
        return output_path

    @classmethod
    def generate_ass(
        cls,
        segments: List[ScriptSegment],
        output_path: Path,
        style: SubtitleStyle = SubtitleStyle.BOTTOM_CENTER,
        video_width: int = 1080,
        video_height: int = 1920,
        font_name: str = "Arial",
        font_size: int = 42,
    ) -> Path:
        """
        Exports segments to an Advanced SubStation Alpha (.ass) subtitle file with rich styling.
        """
        output_path.parent.mkdir(parents=True, exist_ok=True)

        # Alignment: 2 = Bottom-Center, 5 = Middle-Center, 8 = Top-Center
        alignment = 2
        margin_v = 120
        if style == SubtitleStyle.CENTER:
            alignment = 5
            margin_v = 0
        elif style == SubtitleStyle.TOP_CENTER:
            alignment = 8
            margin_v = 120

        header = f"""[Script Info]
; Script generated by GenVid.AI MoneyPrinterTurbo
Title: Production Video Subtitles
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: None
PlayResX: {video_width}
PlayResY: {video_height}

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,{font_name},{font_size},&H00FFFFFF,&H000000FF,&H00000000,&H80000000,-1,0,0,0,100,100,0,0,1,3.5,1.5,{alignment},40,40,{margin_v},1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""
        dialogue_lines: List[str] = []
        for seg in segments:
            start_str = cls.format_timestamp_ass(seg.start_second)
            end_str = cls.format_timestamp_ass(seg.end_second)
            text_clean = seg.text.strip().replace("\n", "\\N")
            dialogue_lines.append(f"Dialogue: 0,{start_str},{end_str},Default,,0,0,0,,{text_clean}")

        full_content = header + "\n".join(dialogue_lines) + "\n"
        output_path.write_text(full_content, encoding="utf-8")
        logger.info(f"Generated ASS subtitles ({len(segments)} lines) → {output_path}")
        return output_path

    @classmethod
    def get_ffmpeg_subtitle_filter(
        cls,
        subtitle_path: Path,
        style: SubtitleStyle = SubtitleStyle.BOTTOM_CENTER,
    ) -> str:
        """
        Constructs an FFmpeg video filter argument for hard-burning subtitles.
        Properly escapes Windows drive colons and backslashes for FFmpeg syntax.
        """
        sub_str = str(subtitle_path.resolve()).replace("\\", "/")
        # Escape colons for FFmpeg filter parsing on Windows (e.g. C\:/path/...)
        sub_escaped = sub_str.replace(":", "\\:")

        if subtitle_path.suffix.lower() == ".ass":
            return f"ass='{sub_escaped}'"
        else:
            # SRT filter with inline force_style
            font_size = 20 if "1080" in sub_str else 18
            return (
                f"subtitles='{sub_escaped}':force_style='"
                f"FontName=Arial,FontSize={font_size},PrimaryColour=&H00FFFFFF,"
                f"OutlineColour=&H00000000,BorderStyle=1,Outline=2,Shadow=1,Alignment=2,MarginV=40'"
            )
